### ISSUE TITLE
逻辑组任务

### ISSUE THREAD

**Issue by wangqr** [wangqr/dummy#1]
# 参考任务量 ts17

第一行为原平台组，第二行为原逻辑组。不包括选手工程。

![hell](https://cloud.githubusercontent.com/assets/8182182/18834964/5fda1a28-842b-11e6-9911-19477ba4452b.png)
# 逻辑部分 （3）

主要是指每回合的结算逻辑。
## 所有技能结算

从技能施放队列中读取所有该回合的技能并进行合法性判定和局面更新。
## 死亡判定和生产结算

结算局面内的单位消失和生成。
## 建筑占领和移动结算

结算建筑物占领，更新全局buff，结算单位移动。
# 通信部分（4）

结算逻辑以外的部分。
## Python端通信

利用socket接收各部分发来的信息，并把操作存放至GameMain类中合适的事件队列供下次结算使用。每回合结算完成之后将局面以一定方式经由socket发送给选手和界面。
## 选手文件（C）及界面代码（C#）

编写非Python平台的相应的socket通信部分。选手文件部分还包括必要的工程文件（CMake，VS，etc.）。界面部分还包括人机对战的伪AI的指令发送。
## 平台程序入口

提供基本的命令行接口，可以直接通过stdin或命令行参数指定双方AI、地图、游戏模式（常规赛/测试赛、调试模式）等信息，以及回放文件位置、结果文件位置、socket监听端口等杂项。游戏运行前能够依次进行版本检查、启动通信的相关代码、回放器、选手的AI等，调试模式下能够从stdio对游戏进行一定程度的控制、局面查看。
## 回放器

游戏回放文件的格式设计和读写操作，需要注意回放时可能需要前后跳转，版本间回放文件如不兼容应做检查。

**Comment by cathera** [comment]
py端通信

**Comment by JackieXuw** [comment]
通信

**Comment by JackieXuw** [comment]
Python端通信

**Comment by wangqr** [comment]
@JackieXuw @cathera 你们二位重了

**Comment by JackieXuw** [comment]
平台程序入口

**Comment by huangyoujia** [comment]
选手文件及平台代码

**Comment by franklore** [comment]
通信

**Comment by wangqr** [comment]
@franklore 通信部分只剩回放器了…

**Comment by wangqr** [comment]
Teamstyle18 is over and now we are working on ts19.
